---
   - name: установка докер блок
     block:
      - name: добавляем репозиториторий где хранятся дистрибутивы линукс
        apt_repository:
         repo: "deb http://us.archive.ubuntu.com/ubuntu/ {{ ansible_distribution_release }} universe"
         state: present
      
      - name: установка доп пакетов для докера
        apt:
         name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
         update-cache: yes
         cache_valid_time: 86400

      - name: добавление ключа докер
        apt_key:
         url: https://download.docker.com/linux/ubuntu/gpg
         state: present

      - name:  установка стабильного репозитория
        apt_repository:                               
         repo: >                            
          deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] 
          https://download.docker.com/linux/ubuntu 
          {{ ansible_distribution_release }} stable
         state: present
         update-cache: yes
         filename: docker

      - name: установка docker-ce
        apt:
         name: docker-ce
         update-cache: yes

      - name: проверка установлен ли  докер
        service:
         name: docker
         state: restarted
         enabled: yes
     become: yes
   - name: завершение установки 
     block:
      - name: добавление пользователя в группу 
        user:
         name: "{{ ansible_user }}"
         group: docker
         append: yes
      - name: перезагрузка
        reboot:      
     become: yes

